= Decks

A repository of my presentation slide decks and workshops.

The presentations are written in AsciiDoc, generated by the AsciiDoc toolchain and presented in HTML5 using dzslides.

== Setting up the build environment

Follow these instructions (for *nix) to setup AsciiDoc to generate dzslide presentatations from the AsciiDoc source file:

First, install http://asciidoc.org[AsciiDoc]. Ensure that the command `asciidoc` is available on your `PATH`.

Next, set the environment variable `DECKS` to where you want to checkout this repository:

----
DECKS=$HOME/mojavelinux-slide-decks
----

Finally, fetch and setup the backend, dzslides and the decks.

----
mkdir -p $HOME/.asciidoc/backends
cd $HOME/.asciidoc/backends
git clone git://github.com/mojavelinux/asciidoc-dzslides-backend.git dzslides
cd dzslides
git clone git://github.com/mojavelinux/dzslides.git
mkdir -p $DECKS
cd $DECKS
git clone git://github.com/mojavelinux/decks.git ${DECKS##*/}
----

== Presentation build instructions

Follow these build instructions to generate a dzslide presentation from the AsciiDoc source files.

First, set the `DECK` environment variable to the name of the folder for the presentation you want to generate:

----
DECK=awestruct-git
----

Next, change into that directory:

----
cd $DECKS/$DECK
----

Next, generate a standalone HTML file that embeds all assets (stylesheets, JavaScript sources and images).

----
asciidoc -a data-uri -a linkcss! slides.asciidoc
----

You can now view the presentation slides.html in your browser.

[NOTE]
====
If you get the following warning:

 asciidoc: WARNING: slides.asciidoc: line 37: missing style: [blockdef-listing]: qrcode

...it means you need to install the AsciiDoc qrcode filter.
====

If you want to link to the assets, you can just run the asciidoc command without any arguments:

----
asciidoc slides.asciidoc
----

However, you also need to create a symlink to the dzslides project so that the linked assets can be located.

----
ln -s $HOME/.asciidoc/backends/dzslides/dzslides dzslides
----

Enjoy!
